Fix compilation issue due to rate-limiter-flexible
## Context

Trying to compile an app with `@gitbeaker/rest` as a dependency would result in an error:
```
Error: Failed to compile '../../node_modules/@gitbeaker/rest/node_modules/rate-limiter-flexible/lib/component/index.d.ts':
  × Module parse failed:
  ╰─▶   × JavaScript parse error: Expected ',', got '?'
         ╭─[3:21]
       1 │ export class RateLimiterQueueError extends Error {
       2 │
       3 │   constructor(message?: string, extra?: string);
         ·                      ─
       4 │
       5 │   readonly name: string;
         ╰────

  help:
        You may need an appropriate loader to handle this file type.
```

The issue is due to `rate-limiter-flexible`, which is fixed in [this commit](https://github.com/animir/node-rate-limiter-flexible/commit/cca3d0c1187a3be77efff726d35f494f04cae1ad) included in [v8.0.1](https://github.com/animir/node-rate-limiter-flexible/releases/tag/v8.0.1).

## Changes

Version up `rate-limiter-flexible` to `^8.0.1`.